name: "Tests"

on:
  - "push"

jobs:
  tests:

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v4"
      - name: "Setup PHP Action"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.2"

      - name: "Download phpmetrics"
        run: "wget https://github.com/phpmetrics/PhpMetrics/raw/master/releases/phpmetrics.phar -P ./"

      - name: "Make phpmetrics executable"
        run: "chmod +x phpmetrics.phar"

      - name: "Get repository name"
        id: "repository"
        run: echo "name=`echo ${{ github.repository }} | cut -d/ -f2`" >> $GITHUB_OUTPUT

      - name: "Run phpmetrics and add Repository name to the result"
        run: |
          ./phpmetrics.phar app/code/ --report-summary-json=./phpmetrics/${{ steps.repository.outputs.name }}.json
          sed -i '1s/.*/{\n    "repository": "${{ steps.repository.outputs.name }}",/' ./phpmetrics/${{ steps.repository.outputs.name }}.json

      - name: "Show generated summary report"
        run: "cat ./*.json"
